### ISSUE TITLE
DRYing out tests, time permiting

### ISSUE THREAD

**Issue by JacobMcFarlane** [UBC-MDS/sktidy#29]
This code chunk shows up in pretty much all our tests:
```python 
X = datasets.load_iris(return_X_y=True, as_frame=True)[0]
y = datasets.load_iris(return_X_y=True, as_frame=True)[1]
z = np.random.rand(X.shape[1])
```

It would probably make sense to unload it into a pytest fixture. Don't know if this is something we necessarily need to address for this week but I figured it was worth making a note.

**Comment by anodaini** [comment]
Sounds like a great idea! Let's plan to do that for milestone 3. Thanks Jacob for the suggestion!
