### ISSUE TITLE
Helper functions?

### ISSUE THREAD

**Issue by JacobMcFarlane** [UBC-MDS/sktidy#30]
Our functions reuse a bit of code (see the block and a couple other places)
```  python
# raise error when model is not fitted yet
check_is_fitted(model)

# raise error when X is not a pandas dataframe object
 if not isinstance(X, pd.core.frame.DataFrame):
      raise TypeError("Input X should be of type 'pandas.core.frame.DataFrame'.")
```

We might want to consider adding helper functions to not repeat this each function (time permitting)

**Comment by anodaini** [comment]
Interesting idea. I find that these lines are clear in what they do and I am afraid not using them in this way may add unnecessary complexity. We can discuss this in our meeting next week. Thanks, Jacob!
