### ISSUE TITLE
License Discussion 

### ISSUE THREAD

**Issue by heidi-ye** [UBC-MDS/sktidy#41]
Opening issue for license discussion. More to come!

Link to R discussion [here](https://github.com/UBC-MDS/sptidy/issues/35).

**Comment by anodaini** [comment]
My suggestion is that we keep the MIT license. Since our package idea is adapted from the broom package (an open-source package), I don't think we would want to put restrictions to use, copy, modify, ..., or sell, yet we still want to free ourselves of liability so I think we should keep the MIT license. Thoughts?

**Comment by heidi-ye** [comment]
Hey Team, 

I was thinking we probably want to stick with a commonly used licenses for simplicity and interpretability. Some options we can consider are:

1. Keep MIT license: This is the most permissive license and in general I don't see any issues with us making the package accessibility as open as possible. Pretty much agree with what @anodaini said above ☝️ 

2. Switch to GNU license: Offers us a little more control if we expect future contributors. They will need to include the full source code, use the same license, etc... I think the biggest advantage of selecting this one is that it allows us to be little more cautious in case we change our mind about the project later on. 

I also found these resources kind of helpful:
- https://gist.github.com/nicolasdao/a7adda51f2f185e8d2700e1573d8a633
- https://www.quora.com/What-is-the-difference-between-open-source-licenses-MIT-CC0-Apache-GNU-etc

Thoughts?

**Comment by xudong-Y** [comment]
Hi Team,

I think we should keep the MIT license. Switching to GNU would require us to disclose all the source code as well, and given that our package is wrapper on sklearn, I believe that's a little challenging. 

In addition, if we have extra time and resource, the Hippocratic License is something we could look into. Given that our package gives an easy way to analyze the model results, we do not want people to use it in an unethical way. 

Thoughts?

**Comment by anodaini** [comment]
Great discussion team. I agree with Peter regarding the GNU license. As for the Hippocratic License, I am not sure we should adopt it as it is still relatively new. My initial thoughts on it were that "code that may lead to harming other people" is a subjective matter. For example, one could argue youtube recommendation systems are harming people and manipulating them but that is not the only way to look at it. I personally am cautious about the vagueness of the Hippocratic License language in terms of what qualifies as harm.

**Comment by heidi-ye** [comment]
@anodaini @xudongyang2, these are good points! It's sounding like the MIT license is the best fit for what we need. Let's go ahead and keep that for both the sktidy and sptidy packages.
